prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    retention: 14d
    retentionSize: 10GB
    resources:
      requests:
        memory: 512Mi
        cpu: 250m
      limits:
        memory: 2Gi
        cpu: 1000m
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn-single
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 20Gi

  alertmanager:
    enabled: true
    alertmanagerSpec:
      configSecret: alertmanager-config
      resources:
        requests:
          memory: 128Mi
          cpu: 100m
        limits:
          memory: 256Mi
          cpu: 200m
      storage:
        volumeClaimTemplate:
          spec:
            storageClassName: longhorn-single
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi

grafana:
  enabled: false

nodeExporter:
  enabled: true

kubeStateMetrics:
  enabled: true
