prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    scrapeInterval: 120s
    retention: 12h
    resources:
      requests:
        memory: 256Mi
        cpu: 100m
      limits:
        memory: 768Mi
        cpu: 500m

  alertmanager:
    enabled: false

grafana:
  enabled: false

nodeExporter:
  enabled: true

kubeStateMetrics:
  enabled: true
