deployment:
  replicas: 2

service:
  type: ClusterIP

providers:
  kubernetesCRD:
    enabled: true
  kubernetesIngress:
    enabled: true

ingressClass:
  enabled: true
  isDefaultClass: false
  name: traefik-external

ports:
  web:
    port: 8000
    expose:
      default: true
    exposedPort: 80
    redirectTo:
      port: websecure

  websecure:
    port: 8443
    expose:
      default: true
    exposedPort: 443
    tls:
      enabled: true

  webwiredoor:
    port: 8081
    expose:
      default: true
    exposedPort: 8081
    protocol: TCP

api:
  dashboard: true
  insecure: true

ingressRoute:
  dashboard:
    enabled: true

logs:
  general:
    level: INFO

accessLogs:
  enabled: true

metrics:
  prometheus:
    enabled: trueß∑