apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - longhorn-single-storageclass.yaml
  - authentik/cluster.yaml
  - authentik/externalsecret.yaml
  - authentik/pooler-ro.yaml
  - authentik/pooler-rw.yaml
  - authentik/pooler-rw-session.yaml
  - authentik/scheduled-backup.yaml
