apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zulip-config
  namespace: zulip
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: zulip-config
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: SETTING_SOCIAL_AUTH_OIDC_ENABLED_IDPS
      remoteRef:
        key: twinbox/global/zulip-oidc
        property: SETTING_SOCIAL_AUTH_OIDC_ENABLED_IDPS
    - secretKey: SECRETS_secret_key
      remoteRef:
        key: twinbox/global/zulip-oidc
        property: SECRETS_secret_key
