apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zulip-config
  namespace: zulip
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: zulip-config
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: SETTING_SOCIAL_AUTH_OIDC_ENABLED_IDPS
      remoteRef:
        key: twinbox/global/zulip-oidc
        property: SETTING_SOCIAL_AUTH_OIDC_ENABLED_IDPS
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
    - secretKey: SECRETS_secret_key
      remoteRef:
        key: twinbox/global/zulip-oidc
        property: SECRETS_secret_key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
    - secretKey: ZULIP_DEFAULT_REALM_OWNER_EMAIL
      remoteRef:
        key: twinbox/global/zulip-oidc
        property: ZULIP_DEFAULT_REALM_OWNER_EMAIL
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
    - secretKey: ZULIP_DEFAULT_REALM_OWNER_NAME
      remoteRef:
        key: twinbox/global/zulip-oidc
        property: ZULIP_DEFAULT_REALM_OWNER_NAME
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
