apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: zulip
  namespace: zulip
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`zulip.__ZONE_NAME__`)
      services:
        - kind: Service
          name: zulip
          port: 80
  tls: {}
