apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zulip-runtime
  namespace: zulip
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: zulip-runtime
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: rabbitmq-password
      remoteRef:
        key: twinbox/global/zulip-runtime
        property: ZULIP_RABBITMQ_PASSWORD
    - secretKey: redis-password
      remoteRef:
        key: twinbox/global/zulip-runtime
        property: ZULIP_REDIS_PASSWORD
