apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wiredoor-gateway
  namespace: wiredoor
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: wiredoor-gateway
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: WIREDOOR_URL
      remoteRef:
        key: twinbox/global/wiredoor-gateway
        property: WIREDOOR_URL
    - secretKey: TOKEN
      remoteRef:
        key: twinbox/global/wiredoor-gateway
        property: TOKEN
