apiVersion: v1
kind: Secret
metadata:
  name: wiredoor-gateway
  namespace: wiredoor
type: Opaque
stringData:
  token: eyJpZCI6MSwidHlwZSI6ImNsaWVudCIsImlhdCI6MTc3NDM3NDQ4MX0.aUJRkLQKSPVrkeL72F0OMuD8qyzfVReES7avMj1xhDk
