apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: wiredoor-gateway-fields
  namespace: wiredoor
spec:
  provider:
    webhook:
      url: "http://bitwarden-cli.bitwarden.svc.cluster.local:8087/object/item/a9a65879-b67b-47e0-b0c2-5e9d30e978ca"
      result:
        jsonPath: "$.data.login.{{ .remoteRef.property }}"
