apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: wiredoor-gateway-fields
  namespace: wiredoor
spec:
  provider:
    webhook:
      url: "http://192.168.2.54:8080/api/secrets/{{ .remoteRef.key }}"
      result:
        jsonPath: "$.data.login.{{ .remoteRef.property }}"
