apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: wiredoor-gateway-fields
  namespace: wiredoor
spec:
  provider:
    webhook:
      url: "http://bitwarden-cli.bitwarden.svc.cluster.local:8087/object/item/d85aac09-6217-4aaa-8fff-dd7d7788cdf4"
      result:
        jsonPath: "$.data.login.{{ .remoteRef.property }}"
