apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - objectstore.yaml
  - cluster.yaml
  - externalsecret.yaml
  - pooler-ro.yaml
  - pooler-rw.yaml
  - pooler-rw-session.yaml
  - scheduled-backup.yaml
