apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vaultwarden-config
  namespace: vaultwarden
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: vaultwarden-config
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: ADMIN_TOKEN
      remoteRef:
        key: twinbox/global/vaultwarden
        property: VAULTWARDEN_ADMIN_TOKEN
    - secretKey: DATABASE_URL
      remoteRef:
        key: twinbox/global/vaultwarden
        property: VAULTWARDEN_DATABASE_URL
