apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn-authentik-callback
  namespace: longhorn-system
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`longhorn.bierineenweek.nl`) && PathPrefix(`/outpost.goauthentik.io`)
      services:
        - kind: Service
          name: authentik-server
          namespace: authentik
          port: 80
  tls: {}
