apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: seaweedfs
  namespace: longhorn-system
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`seaweedfs.__ZONE_NAME__`)
      middlewares:
        - name: authentik-forwardauth
      services:
        - kind: Service
          name: seaweedfs
          port: 8888
  tls: {}
