apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dashy-data
  namespace: dashy
  labels:
    app.kubernetes.io/name: dashy
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
