apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: penpot-bootstrap
  namespace: penpot
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: penpot-bootstrap
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: PENPOT_POSTGRESQL__USERNAME
      remoteRef:
        key: twinbox/global/penpot
        property: PENPOT_POSTGRESQL__USERNAME
    - secretKey: PENPOT_POSTGRESQL__PASSWORD
      remoteRef:
        key: twinbox/global/penpot
        property: PENPOT_POSTGRESQL__PASSWORD
    - secretKey: PENPOT_SECRET_KEY
      remoteRef:
        key: twinbox/global/penpot
        property: PENPOT_SECRET_KEY
    - secretKey: PENPOT_OIDC_CLIENT_ID
      remoteRef:
        key: twinbox/global/penpot
        property: PENPOT_OIDC_CLIENT_ID
    - secretKey: PENPOT_OIDC_CLIENT_SECRET
      remoteRef:
        key: twinbox/global/penpot
        property: PENPOT_OIDC_CLIENT_SECRET
