apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: headlamp
  namespace: kube-system
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`headlamp.__ZONE_NAME__`)
      services:
        - kind: Service
          name: headlamp
          port: 80
  tls: {}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: headlamp-wiredoor
  namespace: kube-system
spec:
  entryPoints:
    - webwiredoor
  routes:
    - kind: Rule
      match: Host(`headlamp.__ZONE_NAME__`)
      services:
        - kind: Service
          name: headlamp
          port: 80
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: headlamp-tailscale
  namespace: kube-system
spec:
  entryPoints:
    - webtailscale
  routes:
    - kind: Rule
      match: Host(`headlamp.__ZONE_NAME__`)
      services:
        - kind: Service
          name: headlamp
          port: 80
  tls: {}
