version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/manager-api"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/manager-web"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/manager-worker"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/portal"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/twinbox-agents"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5

  - package-ecosystem: "docker"
    directory: "/manager-api"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5

  - package-ecosystem: "docker"
    directory: "/manager-worker"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5

  - package-ecosystem: "docker"
    directory: "/manager-web"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5

  - package-ecosystem: "docker"
    directory: "/portal"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5

  - package-ecosystem: "docker"
    directory: "/twinbox-agents"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5

  - package-ecosystem: "docker"
    directory: "/images/jitsi-openid"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
