apiVersion: apps/v1
kind: Deployment
metadata:
  name: stirling-pdf
  namespace: stirling-pdf
  labels:
    app.kubernetes.io/name: stirling-pdf
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: stirling-pdf
  template:
    metadata:
      labels:
        app.kubernetes.io/name: stirling-pdf
    spec:
      containers:
        - name: stirling-pdf
          image: ghcr.io/stirling-tools/stirling-pdf:2.10.0
          imagePullPolicy: IfNotPresent
          env:
            - name: ST_USE_AUTH_FILE
              value: "false"
            - name: SECURITY_CUSTOMGLOBALAPIKEY
              valueFrom:
                secretKeyRef:
                  name: stirling-pdf-config
                  key: STIRLING_PDF_API_KEY
            - name: ST_BASE_URL
              value: https://stirling-pdf.__ZONE_NAME__/
            - name: ST_ENABLE_TRASH_CLEANUP
              value: "true"
            - name: ST_ENABLE_DELETE_ORPHAN_UPLOAD_FOLDERS
              value: "true"
            - name: ST_PDF_AUTO_UPDATE_CONVERTERS
              value: "true"
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 60
            periodSeconds: 20
          startupProbe:
            tcpSocket:
              port: http
            failureThreshold: 90
            periodSeconds: 5
          volumeMounts:
            - name: stirling-pdf-data
              mountPath: /configs
              subPath: configs
            - name: stirling-pdf-data
              mountPath: /customFiles
              subPath: customFiles
            - name: stirling-pdf-data
              mountPath: /logs
              subPath: logs
      volumes:
        - name: stirling-pdf-data
          persistentVolumeClaim:
            claimName: stirling-pdf-data
