apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: stirling-pdf-config
  namespace: stirling-pdf
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: stirling-pdf-config
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: STIRLING_PDF_API_KEY
      remoteRef:
        key: twinbox/global/stirling-pdf
        property: STIRLING_PDF_API_KEY
