apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: searxng-data
  namespace: searxng
  labels:
    app.kubernetes.io/name: searxng
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: searxng-valkey-data
  namespace: searxng
  labels:
    app.kubernetes.io/name: searxng-valkey
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
