apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - pvc.yaml
  - service.yaml
  - deployment.yaml
  - ingressroute.yaml
  - authentik-callback-service.yaml
  - authentik-callback-endpoints.yaml
  - authentik-callback-ingressroute.yaml
