apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: traefik-manager-data
  namespace: traefik-manager
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
