apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: CHANGEME-db-credentials
  namespace: databases
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: CHANGEME-db-credentials
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: username
      remoteRef:
        key: twinbox/global/CHANGEME
        property: CHANGEME_POSTGRESQL__USERNAME
    - secretKey: password
      remoteRef:
        key: twinbox/global/CHANGEME
        property: CHANGEME_POSTGRESQL__PASSWORD
