apiVersion: v1
kind: LimitRange
metadata:
  name: coder-workspaces-defaults
  namespace: coder-workspaces
spec:
  limits:
    - type: "Pod"
      max:
        cpu: "5"
        memory: "9Gi"
      min:
        cpu: "50m"
        memory: "128Mi"
    - type: "Container"
      default:
        cpu: "2"
        memory: "4Gi"
      defaultRequest:
        cpu: "1"
        memory: "2Gi"
      max:
        cpu: "4"
        memory: "8Gi"
      min:
        cpu: "50m"
        memory: "128Mi"
