apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: copyparty-config
  namespace: copyparty
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: copyparty-config
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: COPYPARTY_ADMIN_USERNAME
      remoteRef:
        key: twinbox/global/copyparty
        property: COPYPARTY_ADMIN_USERNAME
    - secretKey: COPYPARTY_ADMIN_PASSWORD
      remoteRef:
        key: twinbox/global/copyparty
        property: COPYPARTY_ADMIN_PASSWORD
    - secretKey: COPYPARTY_FKEY_SALT
      remoteRef:
        key: twinbox/global/copyparty
        property: COPYPARTY_FKEY_SALT
    - secretKey: COPYPARTY_DKEY_SALT
      remoteRef:
        key: twinbox/global/copyparty
        property: COPYPARTY_DKEY_SALT
