apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: hedgedoc
  namespace: hedgedoc
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`hedgedoc.__ZONE_NAME__`)
      services:
        - kind: Service
          name: hedgedoc
          port: 80
  tls: {}
