apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hedgedoc-uploads
  namespace: hedgedoc
  labels:
    app.kubernetes.io/name: hedgedoc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
