apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-oidc
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: grafana-oidc
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: GF_AUTH_DISABLE_LOGIN_FORM
      remoteRef:
        key: twinbox/global/grafana-oidc
        property: GF_AUTH_DISABLE_LOGIN_FORM
    - secretKey: GF_AUTH_OAUTH_AUTO_LOGIN
      remoteRef:
        key: twinbox/global/grafana-oidc
        property: GF_AUTH_OAUTH_AUTO_LOGIN
    - secretKey: GF_AUTH_BASIC_ENABLED
      remoteRef:
        key: twinbox/global/grafana-oidc
        property: GF_AUTH_BASIC_ENABLED
    - secretKey: GF_USERS_AUTO_ASSIGN_ORG_ROLE
      remoteRef:
        key: twinbox/global/grafana-oidc
        property: GF_USERS_AUTO_ASSIGN_ORG_ROLE
    - secretKey: GF_AUTH_GENERIC_OAUTH_ENABLED
      remoteRef:
        key: twinbox/global/grafana-oidc
        property: GF_AUTH_GENERIC_OAUTH_ENABLED
    - secretKey: GF_AUTH_GENERIC_OAUTH_NAME
      remoteRef:
        key: twinbox/global/grafana-oidc
        property: GF_AUTH_GENERIC_OAUTH_NAME
    - secretKey: GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP
      remoteRef:
        key: twinbox/global/grafana-oidc
        property: GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP
    - secretKey: GF_AUTH_GENERIC_OAUTH_CLIENT_ID
      remoteRef:
        key: twinbox/global/grafana-oidc
        property: GF_AUTH_GENERIC_OAUTH_CLIENT_ID
    - secretKey: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
      remoteRef:
        key: twinbox/global/grafana-oidc
        property: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
    - secretKey: GF_AUTH_GENERIC_OAUTH_SCOPES
      remoteRef:
        key: twinbox/global/grafana-oidc
        property: GF_AUTH_GENERIC_OAUTH_SCOPES
    - secretKey: GF_AUTH_GENERIC_OAUTH_AUTH_URL
      remoteRef:
        key: twinbox/global/grafana-oidc
        property: GF_AUTH_GENERIC_OAUTH_AUTH_URL
    - secretKey: GF_AUTH_GENERIC_OAUTH_TOKEN_URL
      remoteRef:
        key: twinbox/global/grafana-oidc
        property: GF_AUTH_GENERIC_OAUTH_TOKEN_URL
    - secretKey: GF_AUTH_GENERIC_OAUTH_API_URL
      remoteRef:
        key: twinbox/global/grafana-oidc
        property: GF_AUTH_GENERIC_OAUTH_API_URL
