apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: affine-db-backup
  namespace: databases
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
  schedule: "0 0 2 * * 2"
  cluster:
    name: affine-db
