apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-wiredoor
  namespace: argocd
spec:
  entryPoints:
    - webwiredoor
  routes:
    - kind: Rule
      match: Host(`argocd.__ZONE_NAME__`)
      services:
        - kind: Service
          name: argocd-server
          port: 443
          scheme: https
          serversTransport: argocd-server-transport
