apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mailu-relay
  namespace: mailu
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: mailu-relay
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: relay-username
      remoteRef:
        key: twinbox/global/mailu-relay
        property: relay-username
    - secretKey: relay-password
      remoteRef:
        key: twinbox/global/mailu-relay
        property: relay-password
