apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mailu-certificates
  namespace: mailu
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: mailu-certificates
    creationPolicy: Owner
    template:
      type: kubernetes.io/tls
  data:
    - secretKey: tls.crt
      remoteRef:
        key: twinbox/global/mailu-certificates
        property: tls.crt
    - secretKey: tls.key
      remoteRef:
        key: twinbox/global/mailu-certificates
        property: tls.key
