apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - externalsecret-certificates.yaml
  - externalsecret-runtime.yaml
  - externalsecret-relay.yaml
  - externalsecret-relay-egress.yaml
  - relay-egress-config.yaml
  - relay-egress.yaml
  - ingressroute.yaml
  - authentik-forwardauth-middleware.yaml
  - netbird-forwarded-headers-middleware.yaml
