apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces.yaml
  - authentik/ingressroute.yaml
  - whoami/ingressroute.yaml
  - headlamp/ingressroute.yaml
  - grafana/ingressroute.yaml
  - grafana/externalsecret.yaml
  - traefik/traefik-dashboard-ingressroute.yaml
  - traefik/argocd-ingressroute.yaml
  - wiredoor-gateway/ingressroute.yaml
  - wiredoor-gateway/externalsecret.yaml
  - homepage/ingressroute.yaml
  - homepage/configmap.yaml
  - homepage/deployment.yaml
  - prometheus/ingressroute.yaml
  - prometheus/alertmanager-config.yaml
  - ntfy/ingressroute.yaml
  - tailscale/externalsecret.yaml
