apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces.yaml
  - authentik/ingressroute.yaml
  - whoami/ingressroute.yaml
  - headlamp/ingressroute.yaml
  - headlamp/externalsecret.yaml
  - grafana/ingressroute.yaml
  - grafana/externalsecret.yaml
  - traefik/traefik-dashboard-ingressroute.yaml
  - traefik/argocd-ingressroute.yaml
  - management-consoles/longhorn-ingressroute.yaml
  - wiredoor-gateway/ingressroute.yaml
  - wiredoor-gateway/externalsecret.yaml
  - dashy/ingressroute.yaml
  - dashy/configmap.yaml
  - dashy/externalsecret.yaml
  - dashy/pvc.yaml
  - dashy/service.yaml
  - dashy/deployment.yaml
  - prometheus/ingressroute.yaml
  - prometheus/alertmanager-config.yaml
  - ntfy/ingressroute.yaml
  - tailscale/externalsecret.yaml
