apiVersion: v1
kind: Namespace
metadata:
  name: dashy
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: tailscale
---
apiVersion: v1
kind: Namespace
metadata:
  name: wiredoor
---
apiVersion: v1
kind: Namespace
metadata:
  name: cloudtty-system
