apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pixelfed-bootstrap
  namespace: pixelfed
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: pixelfed-bootstrap
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: APP_KEY
      remoteRef:
        key: twinbox/global/pixelfed
        property: APP_KEY
    - secretKey: DB_USERNAME
      remoteRef:
        key: twinbox/global/pixelfed
        property: PIXELFED_POSTGRESQL__USERNAME
    - secretKey: DB_PASSWORD
      remoteRef:
        key: twinbox/global/pixelfed
        property: PIXELFED_POSTGRESQL__PASSWORD
    - secretKey: PF_OIDC_CLIENT_ID
      remoteRef:
        key: twinbox/global/pixelfed
        property: PF_OIDC_CLIENT_ID
    - secretKey: PF_OIDC_CLIENT_SECRET
      remoteRef:
        key: twinbox/global/pixelfed
        property: PF_OIDC_CLIENT_SECRET
    - secretKey: PF_OIDC_AUTHORIZE_URL
      remoteRef:
        key: twinbox/global/pixelfed
        property: PF_OIDC_AUTHORIZE_URL
    - secretKey: PF_OIDC_TOKEN_URL
      remoteRef:
        key: twinbox/global/pixelfed
        property: PF_OIDC_TOKEN_URL
    - secretKey: PF_OIDC_PROFILE_URL
      remoteRef:
        key: twinbox/global/pixelfed
        property: PF_OIDC_PROFILE_URL
    - secretKey: PF_OIDC_LOGOUT_URL
      remoteRef:
        key: twinbox/global/pixelfed
        property: PF_OIDC_LOGOUT_URL
