apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pixelfed-bootstrap
  namespace: pixelfed
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: pixelfed-bootstrap
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: APP_KEY
      remoteRef:
        key: twinbox/global/pixelfed
        property: APP_KEY
    - secretKey: DB_USERNAME
      remoteRef:
        key: twinbox/global/pixelfed
        property: PIXELFED_POSTGRESQL__USERNAME
    - secretKey: DB_PASSWORD
      remoteRef:
        key: twinbox/global/pixelfed
        property: PIXELFED_POSTGRESQL__PASSWORD
