apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pixelfed-redis-data
  namespace: pixelfed
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
