apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: collabora
  namespace: nextcloud
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`nextcloud-collabora.__ZONE_NAME__`)
      services:
        - name: nextcloud-collabora
          port: 9980
  tls: {}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: collabora-wiredoor
  namespace: nextcloud
spec:
  entryPoints:
    - webwiredoor
  routes:
    - kind: Rule
      match: Host(`nextcloud-collabora.__ZONE_NAME__`)
      services:
        - name: nextcloud-collabora
          port: 9980
  tls: {}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: collabora-tailscale
  namespace: nextcloud
spec:
  entryPoints:
    - webtailscale
  routes:
    - kind: Rule
      match: Host(`nextcloud-collabora.__ZONE_NAME__`)
      services:
        - name: nextcloud-collabora
          port: 9980
  tls: {}
