apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud-eurooffice
  namespace: nextcloud
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: nextcloud-eurooffice
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: jwt-secret
      remoteRef:
        key: twinbox/global/nextcloud
        property: EUROOFFICE_JWT_SECRET
