apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - admin-externalsecret.yaml
  - db-externalsecret.yaml
  - eurooffice-externalsecret.yaml
  - redis-externalsecret.yaml
  - eurooffice-pvc.yaml
  - eurooffice-deployment.yaml
  - eurooffice-service.yaml
  - eurooffice-forwarded-headers-middleware.yaml
  - middleware.yaml
  - ingressroute.yaml
  - collabora-ingressroute.yaml
  - eurooffice-ingressroute.yaml
