apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - admin-externalsecret.yaml
  - mailu-runtime-externalsecret.yaml
  - db-externalsecret.yaml
  - eurooffice-externalsecret.yaml
  - redis-externalsecret.yaml
  - eurooffice-pvc.yaml
  - eurooffice-deployment.yaml
  - eurooffice-service.yaml
  - eurooffice-forwarded-headers-middleware.yaml
  - middleware.yaml
  - ingressroute.yaml
  - collabora-ingressroute.yaml
  - eurooffice-ingressroute.yaml
  - signaling-externalsecret.yaml
  - signaling-deployment.yaml
  - signaling-service.yaml
  - signaling-ingressroute.yaml
  - coturn-externalsecret.yaml
  - coturn-configmap.yaml
  - coturn-deployment.yaml
  - coturn-service.yaml
  - coturn-turn-certificate.yaml
  - coturn-turn-ingressroutetcp.yaml
  - nats-deployment.yaml
  - nats-service.yaml
  - recording-externalsecret.yaml
  - recording-deployment.yaml
  - recording-service.yaml
  - recording-pvc.yaml
  - recording-ingressroute.yaml