apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - admin-externalsecret.yaml
  - authentik-externalsecret.yaml
  - db-externalsecret.yaml
  - redis-externalsecret.yaml
  - middleware.yaml
  - ingressroute.yaml
  - collabora-ingressroute.yaml
