apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-recording
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi