apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud-redis
  namespace: nextcloud
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: nextcloud-redis
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: password
      remoteRef:
        key: twinbox/global/nextcloud
        property: NEXTCLOUD_REDIS_PASSWORD
