apiVersion: v1
kind: Service
metadata:
  name: adguard-dns
  namespace: adguard
  labels:
    app.kubernetes.io/name: adguard
spec:
  ports:
    - name: dns-udp
      port: 53
      protocol: UDP
    - name: dns-tcp
      port: 53
      protocol: TCP
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app.kubernetes.io/name: adguard
