#!/usr/bin/env bash
# Shared Authentik authentication helper.
# Sources openbao-secret-sync.sh prerequisite.
#
# Usage:
#   source "$WORKSPACE_ROOT/scripts/manager/authentik-auth.sh"
#   authentik_ensure_token
#   echo "$AUTHENTIK_TOKEN"        # usable for API calls or OpenTofu AUTHENTIK_TOKEN env
#   echo "$AUTHENTIK_API_BASE"     # base URL for API calls (if forward set up)

set -euo pipefail

AUTHENTIK_AUTH_LOG_PREFIX="${AUTHENTIK_AUTH_LOG_PREFIX:-Authentik}"

_authentik_log() {
  echo "[$(date '+%Y-%m-%d %H:%M:%S')] ${AUTHENTIK_AUTH_LOG_PREFIX}: $*"
}

_authentik_fail() {
  echo "[$(date '+%Y-%m-%d %H:%M:%S')] ${AUTHENTIK_AUTH_LOG_PREFIX} ERROR: $*" >&2
  exit 1
}

# ---------------------------------------------------------------------------
# Read the shared Authentik secret from OpenBao (populates the variables below)
# ---------------------------------------------------------------------------
authentik_load_bootstrap_secret() {
  if [[ -n "${_AUTHENTIK_SECRET_LOADED:-}" ]]; then
    return 0
  fi

  command -v openbao_read_global_secret_json >/dev/null 2>&1 || \
    _authentik_fail "openbao_read_global_secret_json not available – source openbao-secret-sync.sh first"

  local secret_json
  secret_json="$(openbao_read_global_secret_json authentik)"
  [[ -n "$secret_json" && "$secret_json" != "null" ]] || \
    _authentik_fail "Could not read authentik secret from OpenBao"

  AUTHENTIK_BOOTSTRAP_TOKEN="$(jq -r '.AUTHENTIK_BOOTSTRAP_TOKEN // empty' <<<"$secret_json")"
  AUTHENTIK_BOOTSTRAP_PASSWORD="$(jq -r '.AUTHENTIK_BOOTSTRAP_PASSWORD // empty' <<<"$secret_json")"
  AUTHENTIK_HOST="$(jq -r '.AUTHENTIK_HOST // empty' <<<"$secret_json")"

  [[ -n "$AUTHENTIK_BOOTSTRAP_TOKEN" ]] || _authentik_fail "AUTHENTIK_BOOTSTRAP_TOKEN missing from OpenBao"
  [[ -n "$AUTHENTIK_BOOTSTRAP_PASSWORD" ]] || _authentik_fail "AUTHENTIK_BOOTSTRAP_PASSWORD missing from OpenBao"

  _AUTHENTIK_SECRET_LOADED=1
}

# ---------------------------------------------------------------------------
# Populate AUTHENTIK_TOKEN from OpenBao.
# The AUTHENTIK_BOOTSTRAP_TOKEN is generated by install-authentik-idp via
# "openssl rand -hex 16" and passed to the Authentik deployment as an env var.
# Authentik accepts this same value as a Bearer token for all API calls.
# ---------------------------------------------------------------------------
authentik_ensure_token() {
  authentik_load_bootstrap_secret
  AUTHENTIK_TOKEN="$AUTHENTIK_BOOTSTRAP_TOKEN"
}

# ---------------------------------------------------------------------------
# Set up a kubectl port-forward to Authentik and populate AUTHENTIK_API_BASE
# Call this before making direct API calls that need a local forward.
# Sets: AUTHENTIK_API_BASE, AUTHENTIK_FORWARD_PID, AUTHENTIK_FORWARD_LOG
# ---------------------------------------------------------------------------
AUTHENTIK_FORWARD_PID=""
AUTHENTIK_FORWARD_LOG=""

authentik_setup_forward() {
  local port="${AUTHENTIK_LOCAL_FORWARD_PORT:-18299}"

  AUTHENTIK_FORWARD_LOG="$(mktemp "${TMPDIR:-/tmp}/authentik-port-forward.XXXXXX.log")"
  kubectl -n authentik port-forward "svc/authentik-server" "${port}:80" >"$AUTHENTIK_FORWARD_LOG" 2>&1 &
  AUTHENTIK_FORWARD_PID="$!"

  local attempt=1
  local attempts=60
  while [[ "$attempt" -le "$attempts" ]]; do
    if curl -fsS "http://127.0.0.1:${port}/-/health/live/" >/dev/null 2>&1; then
      AUTHENTIK_API_BASE="http://127.0.0.1:${port}/api/v3"
      return 0
    fi
    if ! kill -0 "$AUTHENTIK_FORWARD_PID" >/dev/null 2>&1; then
      if [[ -s "$AUTHENTIK_FORWARD_LOG" ]]; then
        tail -n 20 "$AUTHENTIK_FORWARD_LOG" >&2
      fi
      _authentik_fail "Authentik port-forward on 127.0.0.1:${port} exited before ready"
    fi
    sleep 1
    attempt=$((attempt + 1))
  done

  _authentik_fail "Authentik port-forward on 127.0.0.1:${port} did not become ready"
}

authentik_teardown_forward() {
  if [[ -n "${AUTHENTIK_FORWARD_PID:-}" ]]; then
    kill "$AUTHENTIK_FORWARD_PID" >/dev/null 2>&1 || true
    wait "$AUTHENTIK_FORWARD_PID" >/dev/null 2>&1 || true
  fi
  rm -f "${AUTHENTIK_FORWARD_LOG:-}"
}

# Register teardown on EXIT if this file was sourced in a script that uses it.
# Only register once per process.
if [[ -z "${_AUTHENTIK_FORWARD_TRAP_SET:-}" ]]; then
  trap 'authentik_teardown_forward' EXIT
  _AUTHENTIK_FORWARD_TRAP_SET=1
fi
