apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: beszel-agent-credentials
  namespace: beszel
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: beszel-agent-credentials
    creationPolicy: Owner
  data:
    - secretKey: key
      remoteRef:
        key: twinbox/global/beszel-agent
        property: key
    - secretKey: token
      remoteRef:
        key: twinbox/global/beszel-agent
        property: token
