apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: crowdsec-bouncer-keys
  namespace: crowdsec
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: crowdsec-bouncer-keys
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: BOUNCER_KEY_traefik
      remoteRef:
        key: twinbox/global/crowdsec-bouncer
        property: lapi_key
