apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: crowdsec-lapi-secrets
  namespace: crowdsec
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: crowdsec-lapi-secrets
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: csLapiSecret
      remoteRef:
        key: twinbox/global/crowdsec-lapi
        property: csLapiSecret
    - secretKey: registrationToken
      remoteRef:
        key: twinbox/global/crowdsec-lapi
        property: registrationToken
