"""
API router for kubeconfig download.

Endpoints:
- GET /api/cluster/{id}/kubeconfig - Download cluster kubeconfig
"""

import logging
from typing import Optional
from uuid import UUID
from pathlib import Path

from fastapi import APIRouter, Depends, HTTPException, status, Request
from fastapi.responses import FileResponse, Response
from sqlalchemy.orm import Session

from manager.shared.database import Cluster, get_db
from manager.shared.security import decrypt_credentials

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api", tags=["clusters"])


@router.get(
    "/cluster/{cluster_id}/kubeconfig",
    summary="Download kubeconfig",
    description="Download the kubeconfig file for a cluster"
)
def get_kubeconfig(
    cluster_id: UUID,
    request: Request,
    db: Session = Depends(get_db)
) -> FileResponse:
    """
    Download kubeconfig for a cluster.

    The kubeconfig is stored encrypted in the database or can be retrieved
    from /config/kubeconfig on the management VM.

    Args:
        cluster_id: Cluster UUID
        request: FastAPI request object
        db: Database session

    Returns:
        FileResponse with kubeconfig content as YAML

    Raises:
        HTTPException 404: If cluster not found or kubeconfig unavailable
        HTTPException 500: If decryption fails
    """
    cluster = db.query(Cluster).filter(Cluster.id == cluster_id).first()
    if not cluster:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Cluster {cluster_id} not found"
        )

    if cluster.status != "ready":
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Cluster is not ready (status: {cluster.status})"
        )

    # Try to get kubeconfig from cluster record
    kubeconfig_encrypted = cluster.kubeconfig_encrypted
    if kubeconfig_encrypted:
        try:
            kubeconfig_data = decrypt_credentials(kubeconfig_encrypted)
        except Exception as e:
            logger.error(f"Failed to decrypt kubeconfig: {e}")
            raise HTTPException(
                status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                detail="Failed to decrypt kubeconfig"
            )
    else:
        # Fall back to file-based retrieval
        # In production, this would fetch from the management VM or a config storage
        kubeconfig_path = Path("/config/kubeconfig")
        if kubeconfig_path.exists():
            # Read file directly
            return FileResponse(
                path=str(kubeconfig_path),
                media_type="text/plain",
                filename=f"kubeconfig-{cluster.name}.yaml",
                headers={
                    "Content-Disposition": f'attachment; filename="kubeconfig-{cluster.name}.yaml"'
                }
            )
        else:
            # For now, return a placeholder
            # In production, this would generate kubeconfig or fetch from vault
            kubeconfig_data = f"""# Kubeconfig for cluster: {cluster.name}
# Generated by Twinbox
# Cluster endpoint: {cluster.endpoint or 'pending'}

apiVersion: v1
kind: Config
clusters:
- cluster:
    server: {cluster.endpoint or 'https://pending'}
    certificate-authority-data: <ca-data>
  name: {cluster.name}

users:
- user:
    token: <token>
  name: admin

contexts:
- context:
    cluster: {cluster.name}
    user: admin
  name: {cluster.name}

current-context: {cluster.name}
"""

    # Return as plain text response
    return Response(
        content=kubeconfig_data,
        media_type="text/plain",
        headers={
            "Content-Disposition": f'attachment; filename="kubeconfig-{cluster.name}.yaml"',
            "Content-Type": "text/plain; charset=utf-8",
        }
    )
