apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: coder-db
  namespace: databases
spec:
  instances: 1

  bootstrap:
    initdb:
      database: coder
      owner: coder
      secret:
        name: coder-db-credentials

  storage:
    size: 5Gi
    storageClass: longhorn-single

  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: "1"
      memory: 2Gi

  monitoring:
    enablePodMonitor: true
