apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: coder-db
  namespace: databases
spec:
  instances: 1

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: coder-db-objectstore
        serverName: coder-db

  bootstrap:
    initdb:
      database: coder
      owner: coder
      secret:
        name: coder-db-credentials

  storage:
    size: 5Gi
    storageClass: longhorn-single

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 1Gi

  monitoring:
    enablePodMonitor: true
