apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mastodon-smtp
  namespace: mastodon
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: mastodon-smtp
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: login
      remoteRef:
        key: twinbox/global/mailu-relay
        property: relay-username
    - secretKey: password
      remoteRef:
        key: twinbox/global/mailu-relay
        property: relay-password