apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: matrix-config
  namespace: matrix
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: matrix-config
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: MATRIX_OIDC_ENABLED_IDPS
      remoteRef:
        key: twinbox/global/matrix-oidc
        property: MATRIX_OIDC_ENABLED_IDPS
    - secretKey: MAS_OIDC_CLIENT_ID
      remoteRef:
        key: twinbox/global/matrix-oidc
        property: MAS_OIDC_CLIENT_ID
    - secretKey: MAS_OIDC_CLIENT_SECRET
      remoteRef:
        key: twinbox/global/matrix-oidc
        property: MAS_OIDC_CLIENT_SECRET
    - secretKey: MAS_OIDC_PROVIDER_ULID
      remoteRef:
        key: twinbox/global/matrix-oidc
        property: MAS_OIDC_PROVIDER_ULID
