# Matrix (Synapse) - Public
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: matrix
  namespace: matrix
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`matrix.__ZONE_NAME__`)
      services:
        - kind: Service
          name: ess-synapse
          port: 8008
  tls: {}
---
# Matrix (Synapse) - Public
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: matrix-netbird
  namespace: matrix
spec:
  entryPoints:
    - webnetbird
  routes:
    - kind: Rule
      match: Host(`matrix.__ZONE_NAME__`)
      services:
        - kind: Service
          name: ess-synapse
          port: 8008
---
# Element Web (Chat) - Public
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: chat
  namespace: matrix
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`chat.__ZONE_NAME__`)
      services:
        - kind: Service
          name: ess-element-web
          port: 80
  tls: {}
---
# Element Web (Chat) - Public
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: chat-netbird
  namespace: matrix
spec:
  entryPoints:
    - webnetbird
  routes:
    - kind: Rule
      match: Host(`chat.__ZONE_NAME__`)
      services:
        - kind: Service
          name: ess-element-web
          port: 80
---
# MAS (Account) - Public
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: account
  namespace: matrix
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`account.__ZONE_NAME__`)
      services:
        - kind: Service
          name: ess-matrix-authentication-service
          port: 8080
  tls: {}
---
# MAS (Account) - Public
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: account-netbird
  namespace: matrix
spec:
  entryPoints:
    - webnetbird
  routes:
    - kind: Rule
      match: Host(`account.__ZONE_NAME__`)
      services:
        - kind: Service
          name: ess-matrix-authentication-service
          port: 8080
---
# Element Admin - Public
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: element-admin
  namespace: matrix
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`element-admin.__ZONE_NAME__`)
      services:
        - kind: Service
          name: ess-element-admin
          port: 8080
  tls: {}
---
# Element Admin - Public
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: element-admin-netbird
  namespace: matrix
spec:
  entryPoints:
    - webnetbird
  routes:
    - kind: Rule
      match: Host(`element-admin.__ZONE_NAME__`)
      services:
        - kind: Service
          name: ess-element-admin
          port: 8080
---
# Matrix RTC (Element Call) - Public
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: mrtc
  namespace: matrix
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`mrtc.__ZONE_NAME__`) && PathPrefix(`/sfu/get`)
      services:
        - kind: Service
          name: ess-matrix-rtc-authorisation-service
          port: 8080
    - kind: Rule
      match: Host(`mrtc.__ZONE_NAME__`) && PathPrefix(`/get_token`)
      services:
        - kind: Service
          name: ess-matrix-rtc-authorisation-service
          port: 8080
    - kind: Rule
      match: Host(`mrtc.__ZONE_NAME__`) && PathPrefix(`/`) && !PathPrefix(`/sfu/get`) && !PathPrefix(`/get_token`)
      services:
        - kind: Service
          name: ess-matrix-rtc-sfu
          port: 7880
  tls: {}
---
# Matrix RTC (Element Call) - Public
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: mrtc-netbird
  namespace: matrix
spec:
  entryPoints:
    - webnetbird
  routes:
    - kind: Rule
      match: Host(`mrtc.__ZONE_NAME__`) && PathPrefix(`/sfu/get`)
      services:
        - kind: Service
          name: ess-matrix-rtc-authorisation-service
          port: 8080
    - kind: Rule
      match: Host(`mrtc.__ZONE_NAME__`) && PathPrefix(`/get_token`)
      services:
        - kind: Service
          name: ess-matrix-rtc-authorisation-service
          port: 8080
    - kind: Rule
      match: Host(`mrtc.__ZONE_NAME__`) && PathPrefix(`/`) && !PathPrefix(`/sfu/get`) && !PathPrefix(`/get_token`)
      services:
        - kind: Service
          name: ess-matrix-rtc-sfu
          port: 7880
