import { resolveStepPresentation } from "./step-presentation.js";

const BASE_STATE = {
  status: "ready",
  state: {
    status: "not_started",
    inputs: {},
    outputs: null,
    cluster_id: null,
    error: null,
    updated_at: null,
  },
  latest_job: null,
};

const QUESTION_STEP_DEFS = [
  {
    id: "provision-nodes",
    title: "Deploy Talos Cluster",
    type: "action",
    journey_stage: "setup",
    summary: "Install Talos Linux on separate VMs on the cluster.",
    explanation:
      "Talos Linux is the immutable, Kubernetes-focused operating system that Twinbox uses. This page collects the cluster sizing, placement, and network values before the long installation starts.",
    side_help:
      "Talos Linux is a minimal, secure, API-driven operating system built specifically for running Kubernetes.",
    inputs: [
      {
        id: "scale_percent",
        label: "Cluster scale",
        type: "integer",
        required: true,
        min: 0,
        max: 100,
        default: 90,
        help: "Scale the VM footprint from 0 to 100 percent. The default reserves room on all three Proxmox hosts.",
      },
      {
        id: "worker_disk_percent",
        label: "Worker disk",
        type: "integer",
        required: true,
        min: 10,
        max: 100,
        default: 100,
        help: "Set the worker disk size as a share of the free worker-host disk. Twinbox starts at 100 percent of the space shared across the three Proxmox hosts.",
      },
      {
        id: "controlplane_count",
        label: "Control planes",
        type: "integer",
        required: true,
        min: 1,
        max: 15,
        default: 3,
        help: "Current API range is 1 to 15. The default gives each Proxmox host one control plane.",
      },
      {
        id: "worker_count",
        label: "Workers",
        type: "integer",
        required: true,
        min: 0,
        max: 200,
        default: 3,
        help: "Current API range is 0 to 200. The default gives each Proxmox host one worker.",
      },
      {
        id: "cpu_cores",
        label: "CPU cores",
        type: "integer",
        required: true,
        min: 1,
        max: 64,
        default: 4,
        help: "Worker CPU allocation. Control planes stay fixed at 2 vCPU, while workers use this value.",
      },
      {
        id: "memory_mb",
        label: "Memory MB",
        type: "integer",
        required: true,
        min: 512,
        max: 1048576,
        default: 10240,
        help: "Worker memory allocation. Control planes stay fixed at 3072 MB, while workers default to 10240 MB unless you change the slider.",
      },
      {
        id: "bridge",
        label: "Bridge",
        type: "string",
        required: true,
        default: "vmbr0",
        help: "Proxmox bridge for Talos node traffic.",
      },
      {
        id: "start_vmid",
        label: "Start VMID",
        type: "integer",
        required: true,
        min: 100,
        max: 999999,
        default: 200,
        help: "Seed VMID for the cluster inventory.",
      },
      {
        id: "vip_ip",
        label: "VIP IP",
        type: "ipv4",
        required: true,
        default: "",
        help: "Virtual IP for the Talos control plane.",
      },
      {
        id: "node_prefix_length",
        label: "Prefix length",
        type: "integer",
        required: true,
        min: 1,
        max: 32,
        default: "",
        help: "CIDR prefix for Talos node addresses.",
      },
      {
        id: "gateway_ip",
        label: "Gateway IP",
        type: "ipv4",
        required: true,
        default: "",
        help: "Default gateway for Talos nodes.",
      },
      {
        id: "dns_servers",
        label: "DNS servers",
        type: "string",
        required: true,
        default: "1.1.1.1,8.8.8.8",
        help: "Comma-separated IPv4 DNS servers for Talos nodes.",
      },
    ],
  },
  {
    id: "configure-dns",
    title: "Configure DNS Provider",
    type: "config",
    journey_stage: "setup",
    summary: "Enter your DNS provider details so Twinbox can manage DNS records automatically.",
    explanation:
      "Twinbox uses external-dns to create and update DNS records in your provider. Your API token is stored in a Kubernetes Secret in the cluster.",
    side_help:
      "Pick the DNS provider where your domain is registered. Twinbox needs an API token with permission to create DNS records (e.g. Zone DNS Edit for Cloudflare).",
    inputs: [
      {
        id: "dns_domain",
        label: "DNS Domain",
        type: "string",
        required: true,
        help: "Your domain name (e.g. example.com).",
      },
      {
        id: "dns_provider",
        label: "DNS Provider",
        type: "string",
        required: true,
        help: "Choose the DNS provider that hosts your domain.",
        options: [
          { label: "Cloudflare", value: "cloudflare" },
          { label: "AWS Route 53", value: "aws" },
          { label: "DigitalOcean", value: "digitalocean" },
          { label: "Google Cloud DNS", value: "google" },
        ],
      },
      {
        id: "dns_api_token",
        label: "API Token / Access Key",
        type: "string",
        required: true,
        help: "API token with DNS zone edit permissions.",
      },
      {
        id: "dns_api_secret",
        label: "API Secret Key (optional)",
        type: "string",
        required: false,
        help: "Only required for AWS (Secret Access Key). Leave empty for Cloudflare, DigitalOcean.",
      },
    ],
  },
  {
    id: "choose-ingress-route",
    title: "Choose Ingress Route",
    type: "config",
    journey_stage: "setup",
    summary: "Choose which ingress branch Twinbox should expose for this cluster.",
    explanation:
      "This page records the ingress strategy you want to use. The DNS domain was already configured in the previous step.",
    side_help:
      "Pick one ingress route. Cloudflare Tunnel is shown only for prd clusters. Non-prd clusters keep the slug-prefixed hostname model, so tst with example.com becomes tst.example.com. prd uses hostnames directly under the base domain, such as authentik.example.com.",
    inputs: [
      {
        id: "ingress_route",
        label: "Ingress Route",
        type: "string",
        required: true,
        help: "Choose the ingress branch you want Twinbox to configure.",
        options: [
          { label: "Wiredoor", value: "wiredoor" },
          { label: "NetBird", value: "netbird" },
          { label: "Cloudflare Tunnel", value: "cloudflare-tunnel" },
          { label: "MetalLB", value: "metallb" },
          { label: "Tailscale", value: "tailscale" },
        ],
      },
    ],
  },
  {
    id: "provision-wiredoor-bastion",
    title: "Deploy Wiredoor Bastion Host",
    type: "action",
    journey_stage: "setup",
    ingress_route: "wiredoor",
    summary: "Provision a Wiredoor bastion host on Hetzner Cloud for external access.",
    explanation:
      "This page collects the Hetzner and DNS details needed to create the Wiredoor bastion host.",
    side_help:
      "Create a Hetzner Cloud API token with Read & Write permissions in your Hetzner project before continuing.",
    inputs: [
      {
        id: "hcloud_token",
        label: "Hetzner API Token",
        type: "string",
        required: true,
        help: "Your Hetzner Cloud API token. Create one at https://console.hetzner.cloud/",
      },
      {
        id: "hcloud_location",
        label: "Server Location",
        type: "string",
        required: false,
        default: "fsn1",
        help: "Datacenter location: fsn1, nbg1, or hel1.",
      },
      {
        id: "hcloud_server_type",
        label: "Server Type",
        type: "string",
        required: false,
        default: "cax11",
        help: "Server size: cax11 (ARM64, 2vCPU/4GB), cx22 (x86, 2vCPU/4GB).",
      },
      {
        id: "wiredoor_network",
        label: "WireGuard Network",
        type: "string",
        required: false,
        default: "10.200.0.0/24",
        help: "Internal WireGuard subnet for the VPN tunnel.",
      },
      {
        id: "zone_name",
        label: "Domain Name",
        type: "string",
        required: true,
        help: "Your domain name (for example example.com).",
      },
      {
        id: "ssh_public_key",
        label: "SSH Public Key",
        type: "string",
        required: false,
        help: "Optional: your SSH public key for direct server access.",
      },
    ],
  },
  {
    id: "configure-wiredoor-ingress",
    title: "Configure Wiredoor Ingress",
    type: "action",
    journey_stage: "setup",
    ingress_route: "wiredoor",
    summary: "Set up Wiredoor tunnel access to the cluster.",
    explanation:
      "This page collects the Wiredoor server details Twinbox will use to register the tunnel.",
    side_help: "You need the Wiredoor server URL and an API token from that server.",
    inputs: [
      {
        id: "wiredoor_url",
        label: "Wiredoor Server URL",
        type: "string",
        required: true,
        help: "The URL of the Wiredoor server, for example https://wiredoor.example.com.",
      },
      {
        id: "wiredoor_token",
        label: "Wiredoor API Token",
        type: "string",
        required: true,
        help: "API token for authenticating with the Wiredoor server.",
      },
      {
        id: "wiredoor_node_name",
        label: "Wiredoor Node Name",
        type: "string",
        required: false,
        help: "Optional custom node name for the Wiredoor tunnel.",
      },
    ],
  },
  {
    id: "configure-cloudflare-dns",
    title: "Configure Cloudflare DNS",
    type: "action",
    journey_stage: "setup",
    ingress_route: "wiredoor",
    summary: "Configure DNS records in Cloudflare for the Wiredoor host.",
    explanation:
      "This page collects the Cloudflare token and domain needed to create the DNS records for your Wiredoor setup.",
    side_help: "Create a Cloudflare API token with Zone DNS Edit permissions before continuing.",
    inputs: [
      {
        id: "cloudflare_api_token",
        label: "Cloudflare API Token",
        type: "string",
        required: true,
        help: "API token with Zone DNS Edit permissions.",
      },
      {
        id: "zone_name",
        label: "Domain Name",
        type: "string",
        required: true,
        help: "Your domain name, for example example.com.",
      },
    ],
  },
  {
    id: "provision-netbird-bastion",
    title: "Deploy NetBird Bastion Host",
    type: "action",
    journey_stage: "setup",
    ingress_route: "netbird",
    summary: "Provision a self-hosted NetBird VPS on Hetzner Cloud.",
    explanation:
      "This step provisions a Hetzner Cloud VM running self-hosted NetBird with the combined NetBird server, dashboard, built-in Traefik, and NetBird Reverse Proxy.",
    side_help:
      "You need a Hetzner Cloud API token. If you also provide Cloudflare credentials, Twinbox creates netbird and proxy DNS records pointing at the new VPS.",
    inputs: [
      {
        id: "hcloud_token",
        label: "Hetzner API Token",
        type: "string",
        required: true,
        help: "Your Hetzner Cloud API token. Create one at https://console.hetzner.cloud/",
      },
      {
        id: "hcloud_location",
        label: "Server Location",
        type: "string",
        required: false,
        default: "fsn1",
        help: "Datacenter location: fsn1 (Falkenstein), nbg1 (Nürnberg), or hel1 (Helsinki)",
      },
      {
        id: "hcloud_server_type",
        label: "Server Type",
        type: "string",
        required: false,
        default: "cax11",
        help: "Server size: cax11 (ARM64, 2vCPU/4GB), cx22 (x86, 2vCPU/4GB)",
      },
      {
        id: "zone_name",
        label: "Domain Name",
        type: "string",
        required: true,
        help: "Root DNS zone name, e.g. example.com",
      },
      {
        id: "netbird_admin_email",
        label: "Let's Encrypt Email",
        type: "string",
        required: true,
        help: "Email address used for NetBird/Traefik Let's Encrypt certificates",
      },
      {
        id: "ssh_public_key",
        label: "SSH Public Key",
        type: "string",
        required: false,
        help: "Optional: Your SSH public key for direct server access",
      },
      {
        id: "cloudflare_api_token",
        label: "Cloudflare API Token",
        type: "string",
        required: false,
        help: "Optional Cloudflare token for netbird/proxy DNS records",
      },
    ],
  },
  {
    id: "configure-netbird-ingress",
    title: "Configure NetBird Ingress",
    type: "action",
    journey_stage: "setup",
    ingress_route: "netbird",
    summary: "Configure NetBird SSO, groups, setup keys, routes, and proxy targets.",
    explanation:
      "This step connects NetBird to Authentik for SSO, creates Twinbox NetBird groups and setup keys with OpenTofu, and records the routing peer credentials in OpenBao for GitOps deployment.",
    side_help:
      "Twinbox already created an admin account and token automatically in the bastion step. You can leave the token field empty in most cases.",
    inputs: [
      {
        id: "netbird_token",
        label: "NetBird API Token",
        type: "string",
        required: false,
        help: "Personal access token from the self-hosted NetBird dashboard. If omitted, Twinbox reads the auto-generated token from the bastion step secrets.",
      },
      {
        id: "netbird_management_url",
        label: "NetBird Management URL",
        type: "string",
        required: false,
        help: "Optional override, defaults to the NetBird VPS URL from the bastion step",
      },
      {
        id: "traefik_resource_address",
        label: "Traefik Resource Address",
        type: "string",
        required: false,
        help: "Optional override, defaults to the Traefik ClusterIP when Kubernetes is reachable",
      },
      {
        id: "proxy_services_json",
        label: "Reverse Proxy Services JSON",
        type: "string",
        required: false,
        help: 'Optional JSON array like [{"name":"portal","domain":"portal.example.com","path":"/"}]',
      },
    ],
  },
  {
    id: "configure-cloudflare-tunnel",
    title: "Configure Cloudflare Tunnel",
    type: "action",
    journey_stage: "setup",
    ingress_route: "cloudflare-tunnel",
    summary: "Expose services through a Cloudflare Tunnel.",
    explanation:
      "This page collects the Cloudflare account details needed to create or reuse the tunnel and DNS record.",
    side_help:
      "Create one Cloudflare custom API token with both Cloudflare Tunnel Edit and DNS Edit permissions.",
    inputs: [
      {
        id: "cf_api_token",
        label: "Cloudflare API Token",
        type: "string",
        required: true,
        help: "One Cloudflare custom token with Tunnel Edit and DNS Edit permissions.",
      },
      {
        id: "cf_account_id",
        label: "Cloudflare Account ID",
        type: "string",
        required: true,
        help: "Your Cloudflare Account ID, found in the dashboard sidebar.",
      },
      {
        id: "cf_zone_id",
        label: "Cloudflare Zone ID",
        type: "string",
        required: true,
        help: "Your Cloudflare Zone ID, found in the Overview tab of the zone.",
      },
    ],
  },
  {
    id: "configure-metallb-ingress",
    title: "Configure MetalLB Ingress",
    type: "action",
    journey_stage: "setup",
    ingress_route: "metallb",
    summary: "Expose services using MetalLB load balancer with port forwarding.",
    explanation:
      "This page collects the LAN IP range and public hostname information MetalLB needs.",
    side_help:
      "You need an available MetalLB IP range, a public hostname, and router port forwarding.",
    inputs: [
      {
        id: "metallb_ip_range",
        label: "MetalLB IP Range",
        type: "string",
        required: true,
        help: "IP range for MetalLB to assign, for example 192.168.1.200-192.168.1.210.",
      },
      {
        id: "public_host",
        label: "Public Hostname",
        type: "string",
        required: true,
        help: "Public hostname pointing to your router.",
      },
      {
        id: "dyndns_provider",
        label: "DynDNS Provider",
        type: "string",
        required: false,
        help: "DynDNS provider name if using dynamic DNS.",
      },
      {
        id: "dyndns_token",
        label: "DynDNS API Token",
        type: "string",
        required: false,
        help: "API token for your DynDNS provider.",
      },
    ],
  },
  {
    id: "configure-tailscale-ingress",
    title: "Configure Tailscale Ingress",
    type: "action",
    journey_stage: "setup",
    ingress_route: "tailscale",
    summary: "Expose services through a Tailscale tailnet.",
    explanation:
      "This page collects the Tailscale or Headscale credentials Twinbox needs to join the cluster to your tailnet.",
    side_help:
      "Generate a Tailscale auth key in the admin console, or provide your Headscale URL and API key.",
    inputs: [
      {
        id: "ts_authkey",
        label: "Tailscale Auth Key",
        type: "string",
        required: true,
        help: "Auth key generated from your Tailscale admin console.",
      },
      {
        id: "ts_tag",
        label: "Tailscale ACL Tag",
        type: "string",
        required: false,
        help: "Optional ACL tag to assign to this node.",
      },
      {
        id: "headscale_url",
        label: "Headscale URL",
        type: "string",
        required: false,
        help: "URL of your self-hosted Headscale instance.",
      },
      {
        id: "headscale_key",
        label: "Headscale API Key",
        type: "string",
        required: false,
        help: "API key for your self-hosted Headscale instance.",
      },
    ],
  },
  {
    id: "create-users-and-groups",
    title: "Create Users and Groups",
    type: "action",
    journey_stage: "setup",
    summary: "Create the first Authentik user and admin group.",
    explanation: "This page collects the first account details Twinbox will use for Authentik.",
    side_help:
      "Use this page to create the account you will use to sign in to Authentik and the protected applications later.",
    inputs: [
      {
        id: "full_name",
        label: "Full name",
        type: "string",
        required: true,
        help: "Display name for the first Authentik user.",
      },
      {
        id: "username",
        label: "Login name",
        type: "string",
        required: true,
        help: "Authentik username for the first user.",
      },
      {
        id: "email",
        label: "Email address",
        type: "string",
        required: false,
        help: "Optional email address for account recovery and profile completeness.",
      },
    ],
  },
];

function decorateStep(step) {
  return {
    ...BASE_STATE,
    ...step,
    ...resolveStepPresentation(step),
  };
}

export function getQuestionSteps(answers = {}) {
  const ingressRoute = answers?.["choose-ingress-route"]?.ingress_route || "";

  return QUESTION_STEP_DEFS.filter(
    (step) => !step.ingress_route || step.ingress_route === ingressRoute
  ).map(decorateStep);
}
