apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: velero-ui-bootstrap
  namespace: velero-ui
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: velero-ui-bootstrap
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: pass_phrase
      remoteRef:
        key: twinbox/global/velero-ui
        property: pass_phrase
    - secretKey: AUTH_SECRET_PASSPHRASE
      remoteRef:
        key: twinbox/global/velero-ui
        property: AUTH_SECRET_PASSPHRASE
    - secretKey: OAUTH_CLIENT_ID
      remoteRef:
        key: twinbox/global/velero-ui
        property: OAUTH_CLIENT_ID
    - secretKey: OAUTH_CLIENT_SECRET
      remoteRef:
        key: twinbox/global/velero-ui
        property: OAUTH_CLIENT_SECRET
    - secretKey: OAUTH_AUTHORIZATION_URL
      remoteRef:
        key: twinbox/global/velero-ui
        property: OAUTH_AUTHORIZATION_URL
    - secretKey: OAUTH_TOKEN_URL
      remoteRef:
        key: twinbox/global/velero-ui
        property: OAUTH_TOKEN_URL
    - secretKey: OAUTH_USER_INFO_URL
      remoteRef:
        key: twinbox/global/velero-ui
        property: OAUTH_USER_INFO_URL
    - secretKey: OAUTH_REDIRECT_URI
      remoteRef:
        key: twinbox/global/velero-ui
        property: OAUTH_REDIRECT_URI
