apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - pvc.yaml
  - service.yaml
  - deployment.yaml
  - oidc-admin-permissions-patch.yaml
  - ingressroute.yaml
  - netbird-forwarded-headers-middleware.yaml
