apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-data
  namespace: audiobookshelf
  labels:
    app.kubernetes.io/name: audiobookshelf
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Gi
