apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: velero
    repoURL: https://vmware-tanzu.github.io/helm-charts
    targetRevision: 5.1.0
    helm:
      values: |
        initContainers:
          - name: velero-plugin-for-aws
            image: velero/velero-plugin-for-aws:v1.8.0
            volumeMounts:
              - mountPath: /target
                name: plugins
        configuration:
          provider: aws
          backupStorageLocation:
            bucket: my-backup-bucket
            config:
              region: minio
              s3ForcePathStyle: true
              s3Url: http://minio.rook-ceph.svc:9000
          volumeSnapshotLocation:
            config:
              region: minio
        credentials:
          useSecret: true
          secretContents:
            cloud: |
              [default]
              aws_access_key_id = minio
              aws_secret_access_key = minio123
  destination:
    server: https://kubernetes.default.svc
    namespace: velero
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
