apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://charts.goauthentik.io
      chart: authentik
      targetRevision: "2026.5.3"
      helm:
        valueFiles:
          - $values/gitops/apps/authentik/values.yaml
    - repoURL: __REPO_URL__
      targetRevision: __TARGET_REVISION__
      ref: values
    - repoURL: __REPO_URL__
      targetRevision: __TARGET_REVISION__
      path: gitops/apps/authentik/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: authentik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
