apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dashy-set
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - clusters:
        selector:
          matchLabels:
            twinbox.io/domain-ready: "true"
  template:
    metadata:
      name: dashy
    spec:
      project: default
      source:
        repoURL: __REPO_URL__
        targetRevision: __TARGET_REVISION__
        path: gitops/platform-apps/dashy
        kustomize:
          patches:
            - target:
                kind: IngressRoute
                name: dashy
              patch: |-
                - op: replace
                  path: /spec/routes/0/match
                  value: Host(`admin.{{index .metadata.annotations "twinbox.io/public-zone-name"}}`)
            - target:
                kind: IngressRoute
                name: dashy-wiredoor
              patch: |-
                - op: replace
                  path: /spec/routes/0/match
                  value: Host(`admin.{{index .metadata.annotations "twinbox.io/public-zone-name"}}`)
            - target:
                kind: IngressRoute
                name: dashy-tailscale
              patch: |-
                - op: replace
                  path: /spec/routes/0/match
                  value: Host(`admin.{{index .metadata.annotations "twinbox.io/public-zone-name"}}`)
            - target:
                kind: Deployment
                name: dashy
              patch: |-
                - op: replace
                  path: /spec/template/spec/containers/0/resources/requests/cpu
                  value: '{{ if eq (index .metadata.labels "twinbox.io/resource-profile") "small" }}25m{{ else if eq (index .metadata.labels "twinbox.io/resource-profile") "large" }}100m{{ else }}50m{{ end }}'
                - op: replace
                  path: /spec/template/spec/containers/0/resources/requests/memory
                  value: '{{ if eq (index .metadata.labels "twinbox.io/resource-profile") "small" }}64Mi{{ else if eq (index .metadata.labels "twinbox.io/resource-profile") "large" }}256Mi{{ else }}128Mi{{ end }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: dashy
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
