apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karakeep
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://karakeep-app.github.io/helm-charts
      chart: karakeep
      targetRevision: "0.31.0"
      helm:
        values: |
          applicationProtocol: https
          applicationHost: karakeep.__ZONE_NAME__
          applicationSecretKey: __KARAKEEP_NEXTAUTH_SECRET__
          meilisearchMasterKey: __KARAKEEP_MEILI_MASTER_KEY__
          controllers:
            karakeep:
              containers:
                karakeep:
                  env:
                    DISABLE_PASSWORD_AUTH: "true"
                    OAUTH_ALLOW_DANGEROUS_EMAIL_ACCOUNT_LINKING: "true"
                    OAUTH_PROVIDER_NAME: Authentik
                    OAUTH_SCOPE: "openid email profile"
                    OAUTH_WELLKNOWN_URL: "https://authentik.__ZONE_NAME__/application/o/karakeep/.well-known/openid-configuration"
          secrets:
            karakeep:
              enabled: true
              stringData:
                OAUTH_CLIENT_ID: __KARAKEEP_OAUTH_CLIENT_ID__
                OAUTH_CLIENT_SECRET: __KARAKEEP_OAUTH_CLIENT_SECRET__
    - repoURL: __REPO_URL__
      targetRevision: __TARGET_REVISION__
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: karakeep
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
