apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: loki
      targetRevision: "7.3.0"
      helm:
        valueFiles:
          - $values/gitops/values/loki.yaml
    - repoURL: __REPO_URL__
      targetRevision: __TARGET_REVISION__
      ref: values
    - repoURL: __REPO_URL__
      targetRevision: __TARGET_REVISION__
      path: gitops/platform-apps/loki
      kustomize:
        patches:
          - target:
              kind: IngressRoute
              name: loki
            patch: |-
              - op: replace
                path: /spec/routes/0/match
                value: Host(`loki.__ZONE_NAME__`)
          - target:
              kind: IngressRoute
              name: loki-netbird
            patch: |-
              - op: replace
                path: /spec/routes/0/match
                value: Host(`loki.__ZONE_NAME__`)
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
