apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mailu
spec:
  project: default
  sources:
    - repoURL: https://mailu.github.io/helm-charts
      chart: mailu
      targetRevision: "2.7.1"
      helm:
        valueFiles:
          - $values/gitops/values/mailu.yaml
        values: |
          domain: "__ZONE_NAME__"
          hostnames:
            - "mail.__ZONE_NAME__"
          initialAccount:
            domain: "__ZONE_NAME__"
          externalRelay:
            host: "__MAILU_RELAY_TARGET_HOST__"
    - repoURL: __REPO_URL__
      targetRevision: __TARGET_REVISION__
      ref: values
    - repoURL: __REPO_URL__
      targetRevision: __TARGET_REVISION__
      path: gitops/platform-apps/mailu
      kustomize:
        patches:
          - target:
              kind: ConfigMap
              name: mailu-relay-egress
            patch: |-
              - op: replace
                path: /data/RELAY_TARGET_HOST
                value: "__MAILU_RELAY_TARGET_HOST__"
          - target:
              kind: IngressRoute
              name: mailu
            patch: |-
              - op: replace
                path: /spec/routes/0/match
                value: Host(`mail.__ZONE_NAME__`) && PathPrefix(`/webmail`)
              - op: replace
                path: /spec/routes/1/match
                value: Host(`mail.__ZONE_NAME__`)
          - target:
              kind: IngressRoute
              name: mailu-netbird
            patch: |-
              - op: replace
                path: /spec/routes/0/match
                value: Host(`mail.__ZONE_NAME__`) && PathPrefix(`/webmail`)
              - op: replace
                path: /spec/routes/1/match
                value: Host(`mail.__ZONE_NAME__`)
          - target:
              kind: IngressRoute
              name: mailu-webmail-root-redirect
            patch: |-
              - op: replace
                path: /spec/routes/0/match
                value: Host(`__ZONE_NAME__`) && PathPrefix(`/webmail`)
          - target:
              kind: Middleware
              name: webmail-root-redirect
            patch: |-
              - op: replace
                path: /spec/redirectRegex/regex
                value: ^https?://__ZONE_NAME__/webmail(.*)
              - op: replace
                path: /spec/redirectRegex/replacement
                value: "https://mail.__ZONE_NAME__/webmail${1}"
  destination:
    server: https://kubernetes.default.svc
    namespace: mailu
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: baseline
        pod-security.kubernetes.io/audit: baseline
        pod-security.kubernetes.io/warn: baseline
    syncOptions:
      - CreateNamespace=true
