apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: __REPO_URL__
      targetRevision: __TARGET_REVISION__
      path: gitops/platform-apps/n8n
      kustomize:
        patches:
          - target:
              kind: Deployment
              name: n8n
            patch: |-
              - op: replace
                path: /spec/template/spec/containers/0/env/9/value
                value: n8n.__ZONE_NAME__
              - op: replace
                path: /spec/template/spec/containers/0/env/14/value
                value: https://n8n.__ZONE_NAME__
              - op: replace
                path: /spec/template/spec/containers/0/env/15/value
                value: https://n8n.__ZONE_NAME__
          - target:
              kind: IngressRoute
              name: n8n
            patch: |-
              - op: replace
                path: /spec/routes/0/match
                value: Host(`n8n.__ZONE_NAME__`)
          - target:
              kind: IngressRoute
              name: n8n-wiredoor
            patch: |-
              - op: replace
                path: /spec/routes/0/match
                value: Host(`n8n.__ZONE_NAME__`)
          - target:
              kind: IngressRoute
              name: n8n-tailscale
            patch: |-
              - op: replace
                path: /spec/routes/0/match
                value: Host(`n8n.__ZONE_NAME__`)
    - repoURL: __REPO_URL__
      targetRevision: __TARGET_REVISION__
      path: gitops/databases/n8n
  destination:
    server: https://kubernetes.default.svc
    namespace: n8n
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
