apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://nextcloud.github.io/helm/
      chart: nextcloud
      targetRevision: "9.1.0"
      helm:
        values: |
          __NEXTCLOUD_VALUES__
    - repoURL: __REPO_URL__
      targetRevision: __TARGET_REVISION__
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: nextcloud
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
