apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ntfy-set
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - clusters:
        selector:
          matchLabels:
            twinbox.io/domain-ready: "true"
  template:
    metadata:
      name: ntfy
    spec:
      project: default
      sources:
        - repoURL: https://kubereboot.github.io/charts/
          chart: ntfy
          targetRevision: "1.0.0"
          helm:
            valueFiles:
              - $values/gitops/values/ntfy.yaml
            values: |
              config:
                base-url: "https://ntfy.{{index .metadata.annotations "twinbox.io/public-zone-name"}}"
        - repoURL: __REPO_URL__
          targetRevision: __TARGET_REVISION__
          ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: monitoring
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
