apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openbao
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://openbao.github.io/openbao-helm
      chart: openbao
      targetRevision: "0.29.2"
      helm:
        valueFiles:
          - $values/gitops/values/openbao.yaml
    - repoURL: __REPO_URL__
      targetRevision: __TARGET_REVISION__
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: openbao
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
