apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pgadmin4
  namespace: argocd
spec:
  project: default
  source:
    repoURL: __REPO_URL__
    targetRevision: __TARGET_REVISION__
    path: gitops/platform-apps/pgadmin4
    kustomize:
      patches:
        - target:
            kind: IngressRoute
            name: pgadmin4
          patch: |-
            - op: replace
              path: /spec/routes/0/match
              value: Host(`pgadmin4.__ZONE_NAME__`)
        - target:
            kind: IngressRoute
            name: pgadmin4-netbird
          patch: |-
            - op: replace
              path: /spec/routes/0/match
              value: Host(`pgadmin4.__ZONE_NAME__`)
  destination:
    server: https://kubernetes.default.svc
    namespace: pgadmin4
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
