apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: "85.1.1"
      helm:
        valueFiles:
          - $values/gitops/values/prometheus.yaml
    - repoURL: __REPO_URL__
      targetRevision: __TARGET_REVISION__
      ref: values
    - repoURL: __REPO_URL__
      targetRevision: __TARGET_REVISION__
      path: gitops/apps/prometheus/manifests
    - repoURL: __REPO_URL__
      targetRevision: __TARGET_REVISION__
      path: gitops/platform-apps/prometheus
      kustomize:
        patches:
          - target:
              kind: IngressRoute
              name: prometheus
            patch: |-
              - op: replace
                path: /spec/routes/0/match
                value: Host(`prometheus.__ZONE_NAME__`)
          - target:
              kind: IngressRoute
              name: prometheus-wiredoor
            patch: |-
              - op: replace
                path: /spec/routes/0/match
                value: Host(`prometheus.__ZONE_NAME__`)
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/audit: privileged
        pod-security.kubernetes.io/warn: privileged
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
