apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-manager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: __REPO_URL__
    targetRevision: __TARGET_REVISION__
    path: gitops/platform/traefik-manager
    kustomize:
      patches:
        - target:
            kind: Deployment
            name: traefik-manager
          patch: |-
            - op: replace
              path: /spec/template/spec/containers/0/env/2/value
              value: traefik-manager.__ZONE_NAME__
        - target:
            kind: IngressRoute
            name: traefik-manager
          patch: |-
            - op: replace
              path: /spec/routes/0/match
              value: Host(`traefik-manager.__ZONE_NAME__`)
        - target:
            kind: IngressRoute
            name: traefik-manager-wiredoor
          patch: |-
            - op: replace
              path: /spec/routes/0/match
              value: Host(`traefik-manager.__ZONE_NAME__`)
        - target:
            kind: IngressRoute
            name: traefik-manager-tailscale
          patch: |-
            - op: replace
              path: /spec/routes/0/match
              value: Host(`traefik-manager.__ZONE_NAME__`)
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
