apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trivy-operator
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://aquasecurity.github.io/helm-charts
      chart: trivy-operator
      targetRevision: "0.36.0"
      helm:
        valueFiles:
          - $values/gitops/values/trivy-operator.yaml
    - repoURL: __REPO_URL__
      targetRevision: __TARGET_REVISION__
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: trivy-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
