apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: hubble-authentik-callback
  namespace: kube-system
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`hubble.__ZONE_NAME__`) && PathPrefix(`/outpost.goauthentik.io`)
      services:
        - kind: Service
          name: authentik-server
          port: 80
  tls: {}
