{{- $routes := .Values.ingressRoutes | default list -}}
{{- range $index, $route := $routes }}
{{- if gt $index 0 }}
---
{{- end }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $route.name }}
  namespace: {{ $route.namespace }}
spec:
  entryPoints:
{{ toYaml $route.entryPoints | nindent 4 }}
  routes:
    - kind: Rule
      match: {{ $route.match | quote }}
      services:
        - kind: Service
          name: {{ $route.service.name }}
          port: {{ $route.service.port }}
{{- if $route.tls }}
  tls: {}
{{- end }}
{{- end }}
