apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: openwebui-db-backup
  namespace: databases
spec:
  schedule: "0 2 * * *"
  backupOwnerReference: self
  cluster:
    name: openwebui-db
