apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: headwind-mdm-runtime
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: headwind-mdm-runtime
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: SQL_USER
      remoteRef:
        key: twinbox/global/headwind-mdm
        property: HEADWIND_POSTGRESQL__USERNAME
    - secretKey: SQL_PASSWORD
      remoteRef:
        key: twinbox/global/headwind-mdm
        property: HEADWIND_POSTGRESQL__PASSWORD
    - secretKey: ADMIN_PASSWORD
      remoteRef:
        key: twinbox/global/headwind-mdm
        property: HEADWIND_ADMIN_PASSWORD
    - secretKey: DEVICE_ADMIN_PASSWORD
      remoteRef:
        key: twinbox/global/headwind-mdm
        property: HEADWIND_DEVICE_ADMIN_PASSWORD
    - secretKey: SHARED_SECRET
      remoteRef:
        key: twinbox/global/headwind-mdm
        property: HEADWIND_SHARED_SECRET
