apiVersion: v1
kind: ConfigMap
metadata:
  name: opencloud-config
  namespace: opencloud
  labels:
    app.kubernetes.io/name: opencloud
data:
  csp.yaml: |
    directives:
      child-src:
        - "'self'"
      connect-src:
        - "'self'"
        - "blob:"
        - "https://authentik.__ZONE_NAME__/"
        - "https://collabora.__ZONE_NAME__/"
        - "wss://collabora.__ZONE_NAME__/"
        - "https://raw.githubusercontent.com/opencloud-eu/awesome-apps/"
        - "https://update.opencloud.eu/"
      default-src:
        - "'none'"
      font-src:
        - "'self'"
      frame-ancestors:
        - "'self'"
        - "https://opencloud.__ZONE_NAME__"
        - "https://collabora.__ZONE_NAME__"
        - "https://wopiserver.__ZONE_NAME__"
      frame-src:
        - "'self'"
        - "blob:"
        - "https://embed.diagrams.net/"
        - "https://collabora.__ZONE_NAME__/"
        - "https://wopiserver.__ZONE_NAME__/"
      img-src:
        - "'self'"
        - "data:"
        - "blob:"
        - "https://raw.githubusercontent.com/opencloud-eu/awesome-apps/"
        - "https://collabora.__ZONE_NAME__/"
      manifest-src:
        - "'self'"
      media-src:
        - "'self'"
      object-src:
        - "'self'"
        - "blob:"
      script-src:
        - "'self'"
        - "'unsafe-inline'"
        - "https://authentik.__ZONE_NAME__/"
      style-src:
        - "'self'"
        - "'unsafe-inline'"
      worker-src:
        - "'self'"
        - "blob:"
  proxy.yaml: |
    role_assignment:
      driver: oidc
      oidc_role_mapper:
        role_claim: roles
        role_mapping:
          - role_name: admin
            claim_value: opencloudAdmin
          - role_name: user
            claim_value: opencloudUser
  radicale.conf: |
    [server]
    hosts = 0.0.0.0:5232

    [auth]
    type = http_x_remote_user

    [storage]
    filesystem_folder = /data/collections

    [web]
    type = internal

    [rights]
    type = owner_only
  app-registry.yaml: |
    mime_registry:
      application/pdf:
        view: collabora
      application/vnd.openxmlformats-officedocument.wordprocessingml.document:
        view: collabora
      application/vnd.openxmlformats-officedocument.spreadsheetml.sheet:
        view: collabora
      application/vnd.openxmlformats-officedocument.presentationml.presentation:
        view: collabora
