apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: opencloud-bootstrap
  namespace: opencloud
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: opencloud-bootstrap
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: OC_URL
      remoteRef:
        key: twinbox/global/opencloud
        property: OC_URL
    - secretKey: OC_OIDC_ISSUER
      remoteRef:
        key: twinbox/global/opencloud
        property: OC_OIDC_ISSUER
    - secretKey: WEB_OPTION_ACCOUNT_EDIT_LINK_HREF
      remoteRef:
        key: twinbox/global/opencloud
        property: WEB_OPTION_ACCOUNT_EDIT_LINK_HREF
    - secretKey: OC_JWT_SECRET
      remoteRef:
        key: twinbox/global/opencloud
        property: OC_JWT_SECRET
    - secretKey: COLLABORATION_WOPI_SECRET
      remoteRef:
        key: twinbox/global/opencloud
        property: COLLABORATION_WOPI_SECRET
    - secretKey: COLLABORATION_WOPI_SRC
      remoteRef:
        key: twinbox/global/opencloud
        property: COLLABORATION_WOPI_SRC
    - secretKey: IDM_ADMIN_PASSWORD
      remoteRef:
        key: twinbox/global/opencloud
        property: IDM_ADMIN_PASSWORD
    - secretKey: OC_LDAP_BIND_PASSWORD
      remoteRef:
        key: twinbox/global/opencloud
        property: OC_LDAP_BIND_PASSWORD
    - secretKey: COLLABORA_ADMIN_PASSWORD
      remoteRef:
        key: twinbox/global/opencloud
        property: COLLABORA_ADMIN_PASSWORD
    - secretKey: COLLABORA_ADMIN_USER
      remoteRef:
        key: twinbox/global/opencloud
        property: COLLABORA_ADMIN_USER
    - secretKey: COLLABORA_DOMAIN
      remoteRef:
        key: twinbox/global/opencloud
        property: COLLABORA_DOMAIN
    - secretKey: COMPANION_DOMAIN
      remoteRef:
        key: twinbox/global/opencloud
        property: COMPANION_DOMAIN
    - secretKey: IDP_DOMAIN
      remoteRef:
        key: twinbox/global/opencloud
        property: IDP_DOMAIN
    - secretKey: OC_REVA_GATEWAY
      remoteRef:
        key: twinbox/global/opencloud
        property: OC_REVA_GATEWAY
    - secretKey: MICRO_REGISTRY_ADDRESS
      remoteRef:
        key: twinbox/global/opencloud
        property: MICRO_REGISTRY_ADDRESS
    - secretKey: COLLABORATION_APP_NAME
      remoteRef:
        key: twinbox/global/opencloud
        property: COLLABORATION_APP_NAME
    - secretKey: COLLABORATION_APP_PRODUCT
      remoteRef:
        key: twinbox/global/opencloud
        property: COLLABORATION_APP_PRODUCT
    - secretKey: COLLABORATION_APP_ADDR
      remoteRef:
        key: twinbox/global/opencloud
        property: COLLABORATION_APP_ADDR
    - secretKey: COLLABORATION_APP_ICON
      remoteRef:
        key: twinbox/global/opencloud
        property: COLLABORATION_APP_ICON
    - secretKey: COLLABORATION_APP_INSECURE
      remoteRef:
        key: twinbox/global/opencloud
        property: COLLABORATION_APP_INSECURE
    - secretKey: COLLABORATION_CS3API_DATAGATEWAY_INSECURE
      remoteRef:
        key: twinbox/global/opencloud
        property: COLLABORATION_CS3API_DATAGATEWAY_INSECURE
    - secretKey: OC_LDAP_BIND_DN
      remoteRef:
        key: twinbox/global/opencloud
        property: OC_LDAP_BIND_DN
    - secretKey: OC_LDAP_URI
      remoteRef:
        key: twinbox/global/opencloud
        property: OC_LDAP_URI
    - secretKey: OC_LDAP_USER_BASE_DN
      remoteRef:
        key: twinbox/global/opencloud
        property: OC_LDAP_USER_BASE_DN
    - secretKey: OC_LDAP_GROUP_BASE_DN
      remoteRef:
        key: twinbox/global/opencloud
        property: OC_LDAP_GROUP_BASE_DN
    - secretKey: OC_LDAP_USER_FILTER
      remoteRef:
        key: twinbox/global/opencloud
        property: OC_LDAP_USER_FILTER
    - secretKey: OC_LDAP_USER_SCHEMA_ID
      remoteRef:
        key: twinbox/global/opencloud
        property: OC_LDAP_USER_SCHEMA_ID
    - secretKey: OC_LDAP_GROUP_SCHEMA_ID
      remoteRef:
        key: twinbox/global/opencloud
        property: OC_LDAP_GROUP_SCHEMA_ID
    - secretKey: OC_LDAP_DISABLE_USER_MECHANISM
      remoteRef:
        key: twinbox/global/opencloud
        property: OC_LDAP_DISABLE_USER_MECHANISM
    - secretKey: OC_LDAP_SERVER_WRITE_ENABLED
      remoteRef:
        key: twinbox/global/opencloud
        property: OC_LDAP_SERVER_WRITE_ENABLED
    - secretKey: GRAPH_LDAP_SERVER_UUID
      remoteRef:
        key: twinbox/global/opencloud
        property: GRAPH_LDAP_SERVER_UUID
    - secretKey: GRAPH_LDAP_REFINT_ENABLED
      remoteRef:
        key: twinbox/global/opencloud
        property: GRAPH_LDAP_REFINT_ENABLED
    - secretKey: SEARCH_EXTRACTOR_TYPE
      remoteRef:
        key: twinbox/global/opencloud
        property: SEARCH_EXTRACTOR_TYPE
    - secretKey: SEARCH_EXTRACTOR_TIKA_TIKA_URL
      remoteRef:
        key: twinbox/global/opencloud
        property: SEARCH_EXTRACTOR_TIKA_TIKA_URL
    - secretKey: FRONTEND_FULL_TEXT_SEARCH_ENABLED
      remoteRef:
        key: twinbox/global/opencloud
        property: FRONTEND_FULL_TEXT_SEARCH_ENABLED
    - secretKey: WEBFINGER_WEB_OIDC_CLIENT_ID
      remoteRef:
        key: twinbox/global/opencloud
        property: WEBFINGER_WEB_OIDC_CLIENT_ID
    - secretKey: WEBFINGER_WEB_OIDC_CLIENT_SCOPES
      remoteRef:
        key: twinbox/global/opencloud
        property: WEBFINGER_WEB_OIDC_CLIENT_SCOPES
    - secretKey: WEBFINGER_DESKTOP_OIDC_CLIENT_ID
      remoteRef:
        key: twinbox/global/opencloud
        property: WEBFINGER_DESKTOP_OIDC_CLIENT_ID
    - secretKey: WEBFINGER_DESKTOP_OIDC_CLIENT_SCOPES
      remoteRef:
        key: twinbox/global/opencloud
        property: WEBFINGER_DESKTOP_OIDC_CLIENT_SCOPES
    - secretKey: WEBFINGER_ANDROID_OIDC_CLIENT_ID
      remoteRef:
        key: twinbox/global/opencloud
        property: WEBFINGER_ANDROID_OIDC_CLIENT_ID
    - secretKey: WEBFINGER_ANDROID_OIDC_CLIENT_SCOPES
      remoteRef:
        key: twinbox/global/opencloud
        property: WEBFINGER_ANDROID_OIDC_CLIENT_SCOPES
    - secretKey: WEBFINGER_IOS_OIDC_CLIENT_ID
      remoteRef:
        key: twinbox/global/opencloud
        property: WEBFINGER_IOS_OIDC_CLIENT_ID
    - secretKey: WEBFINGER_IOS_OIDC_CLIENT_SCOPES
      remoteRef:
        key: twinbox/global/opencloud
        property: WEBFINGER_IOS_OIDC_CLIENT_SCOPES
    - secretKey: WEB_OIDC_CLIENT_ID
      remoteRef:
        key: twinbox/global/opencloud
        property: WEB_OIDC_CLIENT_ID
    - secretKey: WEB_OIDC_SCOPE
      remoteRef:
        key: twinbox/global/opencloud
        property: WEB_OIDC_SCOPE
    - secretKey: INITIAL_ADMIN_PASSWORD
      remoteRef:
        key: twinbox/global/opencloud
        property: INITIAL_ADMIN_PASSWORD
