apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opencloud-config
  namespace: opencloud
  labels:
    app.kubernetes.io/name: opencloud
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opencloud-data
  namespace: opencloud
  labels:
    app.kubernetes.io/name: opencloud
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opencloud-apps
  namespace: opencloud
  labels:
    app.kubernetes.io/name: opencloud
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opencloud-ldap-data
  namespace: opencloud
  labels:
    app.kubernetes.io/name: opencloud-ldap
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opencloud-ldap-certs
  namespace: opencloud
  labels:
    app.kubernetes.io/name: opencloud-ldap
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opencloud-radicale-data
  namespace: opencloud
  labels:
    app.kubernetes.io/name: opencloud-radicale
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
