apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-bootstrap
  namespace: authentik
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: authentik-bootstrap
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: AUTHENTIK_SECRET_KEY
      remoteRef:
        key: twinbox/global/authentik
        property: AUTHENTIK_SECRET_KEY
    - secretKey: AUTHENTIK_BOOTSTRAP_PASSWORD
      remoteRef:
        key: twinbox/global/authentik
        property: AUTHENTIK_BOOTSTRAP_PASSWORD
    - secretKey: AUTHENTIK_BOOTSTRAP_TOKEN
      remoteRef:
        key: twinbox/global/authentik
        property: AUTHENTIK_BOOTSTRAP_TOKEN
    - secretKey: AUTHENTIK_BOOTSTRAP_EMAIL
      remoteRef:
        key: twinbox/global/authentik
        property: AUTHENTIK_BOOTSTRAP_EMAIL
    - secretKey: AUTHENTIK_AUTOMATION_TOKEN_KEY
      remoteRef:
        key: twinbox/global/authentik
        property: AUTHENTIK_AUTOMATION_TOKEN_KEY
    - secretKey: AUTHENTIK_POSTGRESQL__HOST
      remoteRef:
        key: twinbox/global/authentik
        property: AUTHENTIK_POSTGRESQL__HOST
    - secretKey: AUTHENTIK_POSTGRESQL__PORT
      remoteRef:
        key: twinbox/global/authentik
        property: AUTHENTIK_POSTGRESQL__PORT
    - secretKey: AUTHENTIK_POSTGRESQL__NAME
      remoteRef:
        key: twinbox/global/authentik
        property: AUTHENTIK_POSTGRESQL__NAME
    - secretKey: AUTHENTIK_POSTGRESQL__USER
      remoteRef:
        key: twinbox/global/authentik
        property: AUTHENTIK_POSTGRESQL__USER
    - secretKey: AUTHENTIK_POSTGRESQL__USERNAME
      remoteRef:
        key: twinbox/global/authentik
        property: AUTHENTIK_POSTGRESQL__USERNAME
    - secretKey: AUTHENTIK_POSTGRESQL__PASSWORD
      remoteRef:
        key: twinbox/global/authentik
        property: AUTHENTIK_POSTGRESQL__PASSWORD
    - secretKey: AUTHENTIK_POSTGRESQL__DISABLE_SERVER_SIDE_CURSORS
      remoteRef:
        key: twinbox/global/authentik
        property: AUTHENTIK_POSTGRESQL__DISABLE_SERVER_SIDE_CURSORS
    - secretKey: AUTHENTIK_POSTGRESQL__CONN_MAX_AGE
      remoteRef:
        key: twinbox/global/authentik
        property: AUTHENTIK_POSTGRESQL__CONN_MAX_AGE
    - secretKey: AUTHENTIK_HOST
      remoteRef:
        key: twinbox/global/authentik
        property: AUTHENTIK_HOST
    - secretKey: AUTHENTIK_HOST_BROWSER
      remoteRef:
        key: twinbox/global/authentik
        property: AUTHENTIK_HOST_BROWSER
