apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - externalsecret.yaml
  - pvc.yaml
  - service.yaml
  - deployment.yaml
  - ingressroute.yaml
  - netbird-forwarded-headers-middleware.yaml
  - ingressroute-netbird.yaml

images:
  - name: ghcr.io/harrywesterman/twinbox-portal
    newTag: sha-97d5cda46732712f0b7abb71aaffbbbf894b8b30
