apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: audiobookshelf-set
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - clusters:
        selector:
          matchLabels:
            twinbox.io/domain-ready: "true"
            twinbox.io/app-audiobookshelf: "enabled"
  template:
    metadata:
      name: audiobookshelf
    spec:
      project: default
      source:
        repoURL: https://github.com/harrywesterman/Twinbox.git
        targetRevision: main
        path: gitops/platform-apps/audiobookshelf
        kustomize:
          patches:
            - target:
                kind: IngressRoute
                name: audiobookshelf
              patch: |-
                - op: replace
                  path: /spec/routes/0/match
                  value: Host(`audiobookshelf.{{index .metadata.annotations "twinbox.io/public-zone-name"}}`)
            - target:
                kind: IngressRoute
                name: audiobookshelf-netbird
              patch: |-
                - op: replace
                  path: /spec/routes/0/match
                  value: Host(`audiobookshelf.{{index .metadata.annotations "twinbox.io/public-zone-name"}}`)
      destination:
        server: https://kubernetes.default.svc
        namespace: audiobookshelf
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
