apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jitsi-auth
  namespace: jitsi
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: jitsi-auth
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: JWT_APP_ID
      remoteRef:
        key: twinbox/global/jitsi-auth
        property: JWT_APP_ID
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: JWT_APP_SECRET
      remoteRef:
        key: twinbox/global/jitsi-auth
        property: JWT_APP_SECRET
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: JITSI_SECRET
      remoteRef:
        key: twinbox/global/jitsi-auth
        property: JITSI_SECRET
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: JITSI_URL
      remoteRef:
        key: twinbox/global/jitsi-auth
        property: JITSI_URL
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: JITSI_SUB
      remoteRef:
        key: twinbox/global/jitsi-auth
        property: JITSI_SUB
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: ISSUER_URL
      remoteRef:
        key: twinbox/global/jitsi-auth
        property: ISSUER_URL
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: CLIENT_ID
      remoteRef:
        key: twinbox/global/jitsi-auth
        property: CLIENT_ID
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: CLIENT_SECRET
      remoteRef:
        key: twinbox/global/jitsi-auth
        property: CLIENT_SECRET
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: BASE_URL
      remoteRef:
        key: twinbox/global/jitsi-auth
        property: BASE_URL
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: BROKER_SESSION_SECRET
      remoteRef:
        key: twinbox/global/jitsi-auth
        property: BROKER_SESSION_SECRET
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: JICOFO_AUTH_PASSWORD
      remoteRef:
        key: twinbox/global/jitsi-auth
        property: JICOFO_AUTH_PASSWORD
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: JVB_AUTH_USER
      remoteRef:
        key: twinbox/global/jitsi-auth
        property: JVB_AUTH_USER
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: JVB_AUTH_PASSWORD
      remoteRef:
        key: twinbox/global/jitsi-auth
        property: JVB_AUTH_PASSWORD
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
