apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jitsi-auth
  namespace: jitsi
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: jitsi-auth
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: JWT_APP_ID
      remoteRef:
        key: twinbox/global/jitsi-auth
        property: JWT_APP_ID
    - secretKey: JWT_APP_SECRET
      remoteRef:
        key: twinbox/global/jitsi-auth
        property: JWT_APP_SECRET
    - secretKey: JITSI_SECRET
      remoteRef:
        key: twinbox/global/jitsi-auth
        property: JITSI_SECRET
    - secretKey: JITSI_URL
      remoteRef:
        key: twinbox/global/jitsi-auth
        property: JITSI_URL
    - secretKey: JITSI_SUB
      remoteRef:
        key: twinbox/global/jitsi-auth
        property: JITSI_SUB
    - secretKey: ISSUER_URL
      remoteRef:
        key: twinbox/global/jitsi-auth
        property: ISSUER_URL
    - secretKey: CLIENT_ID
      remoteRef:
        key: twinbox/global/jitsi-auth
        property: CLIENT_ID
    - secretKey: CLIENT_SECRET
      remoteRef:
        key: twinbox/global/jitsi-auth
        property: CLIENT_SECRET
    - secretKey: BASE_URL
      remoteRef:
        key: twinbox/global/jitsi-auth
        property: BASE_URL
    - secretKey: BROKER_SESSION_SECRET
      remoteRef:
        key: twinbox/global/jitsi-auth
        property: BROKER_SESSION_SECRET
