apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-db-credentials
  namespace: databases
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: paperless-db-credentials
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: username
      remoteRef:
        key: twinbox/global/paperless
        property: PAPERLESS_DBUSER
    - secretKey: password
      remoteRef:
        key: twinbox/global/paperless
        property: PAPERLESS_DBPASS
