apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: paperless-db-pooler-rw
  namespace: databases
spec:
  cluster:
    name: paperless-db
  instances: 2
  type: rw
  pgbouncer:
    poolMode: transaction
    parameters:
      max_client_conn: "200"
      default_pool_size: "20"
