apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-config
  namespace: paperless
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: paperless-config
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: PAPERLESS_SECRET_KEY
      remoteRef:
        key: twinbox/global/paperless
        property: PAPERLESS_SECRET_KEY
    - secretKey: PAPERLESS_ADMIN_USER
      remoteRef:
        key: twinbox/global/paperless
        property: PAPERLESS_ADMIN_USER
    - secretKey: PAPERLESS_ADMIN_PASSWORD
      remoteRef:
        key: twinbox/global/paperless
        property: PAPERLESS_ADMIN_PASSWORD
    - secretKey: PAPERLESS_ADMIN_MAIL
      remoteRef:
        key: twinbox/global/paperless
        property: PAPERLESS_ADMIN_MAIL
    - secretKey: PAPERLESS_DBUSER
      remoteRef:
        key: twinbox/global/paperless
        property: PAPERLESS_DBUSER
    - secretKey: PAPERLESS_DBPASS
      remoteRef:
        key: twinbox/global/paperless
        property: PAPERLESS_DBPASS
    - secretKey: PAPERLESS_SOCIALACCOUNT_PROVIDERS
      remoteRef:
        key: twinbox/global/paperless
        property: PAPERLESS_SOCIALACCOUNT_PROVIDERS
