apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - externalsecret.yaml
  - redis.yaml
  - document-converters.yaml
  - deployment.yaml
  - service.yaml
  - ingressroute.yaml
