apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: matrix-mas-db
  namespace: databases
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:16.4

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: matrix-mas-db-objectstore
        serverName: matrix-mas-db

  bootstrap:
    initdb:
      database: matrix_mas
      owner: matrix_mas
      secret:
        name: matrix-mas-db-credentials

  storage:
    size: 10Gi
    storageClass: longhorn-single

  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: "500m"
      memory: 1Gi

  postgresql:
    parameters:
      max_connections: "50"
      shared_buffers: "128MB"
      effective_cache_size: "384MB"
      work_mem: "4MB"

  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname

  monitoring:
    enablePodMonitor: true
