apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: mastodon-db-pooler-rw-session
  namespace: databases
spec:
  cluster:
    name: mastodon-db
  instances: 2
  type: rw
  pgbouncer:
    poolMode: session
    parameters:
      max_client_conn: "200"
      default_pool_size: "20"
