apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: grafana-admin-fields
    kind: SecretStore
  target:
    name: grafana-admin
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: admin-user
      remoteRef:
        key: twinbox/global/grafana
        property: username
    - secretKey: admin-password
      remoteRef:
        key: twinbox/global/grafana
        property: password
