apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: grafana-admin-fields
  namespace: monitoring
spec:
  provider:
    webhook:
      url: "http://bitwarden-cli.bitwarden.svc.cluster.local:8087/object/item/ea9461a9-bffa-4a30-9cc0-3585b78360b1"
      result:
        jsonPath: "$.data.login.{{ .remoteRef.property }}"
