apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: grafana-admin-fields
  namespace: monitoring
spec:
  provider:
    webhook:
      url: "http://bitwarden-cli.bitwarden.svc.cluster.local:8087/object/item/twinbox/global/grafana"
      result:
        jsonPath: "$.data.login.{{ .remoteRef.property }}"
