apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: grafana-admin-fields
  namespace: monitoring
spec:
  provider:
    webhook:
      url: "http://bitwarden-cli.bitwarden.svc.cluster.local:8087/object/item/266a9922-e2a3-4ee0-a53f-7874d9b42ab4"
      result:
        jsonPath: "$.data.login.{{ .remoteRef.property }}"
