apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pgadmin4-oidc
  namespace: pgadmin4
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: pgadmin4-bootstrap
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: PGADMIN_DEFAULT_EMAIL
      remoteRef:
        key: twinbox/global/pgadmin4-oidc
        property: PGADMIN_DEFAULT_EMAIL
    - secretKey: PGADMIN_DEFAULT_PASSWORD
      remoteRef:
        key: twinbox/global/pgadmin4-oidc
        property: PGADMIN_DEFAULT_PASSWORD
    - secretKey: PGADMIN_MASTER_PASSWORD
      remoteRef:
        key: twinbox/global/pgadmin4-oidc
        property: PGADMIN_MASTER_PASSWORD
    - secretKey: PGADMIN_OAUTH2_CLIENT_ID
      remoteRef:
        key: twinbox/global/pgadmin4-oidc
        property: PGADMIN_OAUTH2_CLIENT_ID
    - secretKey: PGADMIN_OAUTH2_CLIENT_SECRET
      remoteRef:
        key: twinbox/global/pgadmin4-oidc
        property: PGADMIN_OAUTH2_CLIENT_SECRET
    - secretKey: PGADMIN_OAUTH2_SERVER_METADATA_URL
      remoteRef:
        key: twinbox/global/pgadmin4-oidc
        property: PGADMIN_OAUTH2_SERVER_METADATA_URL
    - secretKey: PGADMIN_OAUTH2_SCOPE
      remoteRef:
        key: twinbox/global/pgadmin4-oidc
        property: PGADMIN_OAUTH2_SCOPE
