apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin4-data
  namespace: pgadmin4
  labels:
    app.kubernetes.io/name: pgadmin4
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
