apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-wiredoor
  namespace: monitoring
spec:
  entryPoints:
    - webwiredoor
  routes:
    - kind: Rule
      match: Host(`{{ .Values.hosts.grafana }}.{{ .Values.domain }}`)
      services:
        - kind: Service
          name: grafana
          port: 80