apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-db-credentials
  namespace: databases
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: n8n-db-credentials
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: username
      remoteRef:
        key: twinbox/global/n8n
        property: N8N_POSTGRESQL__USERNAME
    - secretKey: password
      remoteRef:
        key: twinbox/global/n8n
        property: N8N_POSTGRESQL__PASSWORD
